{% set version = "0.4.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proj
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/PROJ_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PROJ/PROJ_{{ version }}.tar.gz
  sha256: abef2f862aa3cf62e642990c6fb9ea8735e7331d4ae9b7130e9f5ef0cd1e0347

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - proj
  run:
    - r-base
    - {{ native }}gcc-libs       # [win]

test:
  requires:
    - r-testthat
  source_files:
    - tests/
  commands:
    - $R -e "library('PROJ')"                                                         # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('PROJ')\""                                                # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://github.com/hypertidy/PROJ
  license: GPL-3.0-only
  summary: A wrapper around the generic coordinate transformation software 'PROJ' that transforms
    coordinates from one coordinate reference system ('CRS') to another. This includes
    cartographic projections as well as geodetic transformations.  The intention is
    for this package to be used by user-packages such as 'reproj', and that the older
    'PROJ.4' and version 5 pathways be provided by the 'proj4' package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
